# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meeting_service_pb2 as meeting__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meeting_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeetingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeeting = channel.unary_unary(
                '/meeting.MeetingService/GetMeeting',
                request_serializer=meeting__service__pb2.GetMeetingRequest.SerializeToString,
                response_deserializer=meeting__service__pb2.GetMeetingResponse.FromString,
                _registered_method=True)
        self.AddParticipant = channel.unary_unary(
                '/meeting.MeetingService/AddParticipant',
                request_serializer=meeting__service__pb2.AddParticipantRequest.SerializeToString,
                response_deserializer=meeting__service__pb2.AddParticipantResponse.FromString,
                _registered_method=True)
        self.ListParticipants = channel.unary_unary(
                '/meeting.MeetingService/ListParticipants',
                request_serializer=meeting__service__pb2.ListParticipantsRequest.SerializeToString,
                response_deserializer=meeting__service__pb2.ListParticipantsResponse.FromString,
                _registered_method=True)


class MeetingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParticipants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeeting,
                    request_deserializer=meeting__service__pb2.GetMeetingRequest.FromString,
                    response_serializer=meeting__service__pb2.GetMeetingResponse.SerializeToString,
            ),
            'AddParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddParticipant,
                    request_deserializer=meeting__service__pb2.AddParticipantRequest.FromString,
                    response_serializer=meeting__service__pb2.AddParticipantResponse.SerializeToString,
            ),
            'ListParticipants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParticipants,
                    request_deserializer=meeting__service__pb2.ListParticipantsRequest.FromString,
                    response_serializer=meeting__service__pb2.ListParticipantsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meeting.MeetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meeting.MeetingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeetingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.MeetingService/GetMeeting',
            meeting__service__pb2.GetMeetingRequest.SerializeToString,
            meeting__service__pb2.GetMeetingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.MeetingService/AddParticipant',
            meeting__service__pb2.AddParticipantRequest.SerializeToString,
            meeting__service__pb2.AddParticipantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParticipants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.MeetingService/ListParticipants',
            meeting__service__pb2.ListParticipantsRequest.SerializeToString,
            meeting__service__pb2.ListParticipantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
